Feature/socialmedia
GSM-Space/Petition-Server pull request #11
Opened 2020-12-21 03:21 UTC by sunrabbit123

![image](https://user-images.githubusercontent.com/64676070/102735905-ee711880-4386-11eb-8dd7-6341b5724c30.png)

잘작동은 하는데, 함수나 변수이름 네이밍에 있거나, 알고리즘에 있어서 피드백 부탁드립니다.

2020-12-21 05:07 UTC, hmoon630 requested changes

2020-12-21 05:07 UTC, skyuecx0630 commented on src/controller/auth.py
> +    return res.json()
```suggestion
    return res.json()

```
line ending 빼먹지 말고 넣어주기 :D

2020-12-21 05:07 UTC, skyuecx0630 commented on src/controller/auth.py
> +def auth_account(id_token: str):
```suggestion
def auth_by_token(id_token: str):
```
auth_account 보다는 토큰을 이용해서 인증한다는 이름을 붙여주는게 나을거 같네요

2020-12-21 05:07 UTC, hmoon630 commented on src/controller/student.py
> +    if not check:
계정이 이미 존재할 경우와 존재하지 않는 경우를 두개의 함수로 분리하는게 더 나아보여요 :D

2020-12-21 05:07 UTC, hmoon630 commented on src/controller/student.py
> +def rne(id_token: str):
rne가 무엇의 줄임말인지 잘 짐작이 가질 않는데, 다른 이름을 사용해보는건 어떨까요?

2020-12-21 05:07 UTC, hmoon630 commented on src/routers/api.py
> +    tags=["api", "account", "auth"],
```suggestion
    tags=["auth"],
```
여러가지 태그를 동시에 적으면, swagger나 redoc에서 같은 api가 중복으로 떠요. path에 맞게 auth만 사용하는게 더 나아보여요

2020-12-21 05:07 UTC, hmoon630 commented on src/routers/auth/__init__.py
> +from .auth import auth
```suggestion
from .auth import auth

```
line ending 추가 :D

2020-12-21 08:00 UTC, hmoon630 commented on src/routers/auth/auth.py
> +    return info
```suggestion
    return info

```
line ending 추가

2020-12-21 08:08 UTC, hmoon630 approved these changes

2020-12-21 08:08 UTC, merged

2020-12-22 06:05 UTC, sunrabbit123 commented on src/controller/users.py
> +    account = Users(std_id=data["sub"], email=data["email"], name=data["name"])
data를 어디서 가져오는ㄱ...
코드 잘못짜놨네 마음이 급해서시리